const axios = require('axios');

exports.handler = async (event, context) => {
    // CORS Headers
    const headers = {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'Content-Type',
        'Access-Control-Allow-Methods': 'POST, OPTIONS'
    };

    if (event.httpMethod === 'OPTIONS') {
        return { statusCode: 200, headers, body: '' };
    }

    if (event.httpMethod !== 'POST') {
        return { statusCode: 405, headers, body: 'Method Not Allowed' };
    }

    try {
        const { text, provider } = JSON.parse(event.body);

        if (!text) {
            return {
                statusCode: 400,
                headers,
                body: JSON.stringify({ error: "Text is required" })
            };
        }

        const aiProvider = provider || process.env.DEFAULT_AI_PROVIDER || 'gemini';
        const prompt = `Convert the following text into a well-formatted Markdown document. Use appropriate headers, lists, and formatting to make it look professional. Do not add any conversational text before or after the markdown. Just return the markdown content.\n\nText:\n${text}`;

        let markdown = '';

        switch (aiProvider) {
            case 'openai':
                const openaiRes = await axios.post('https://api.openai.com/v1/chat/completions', {
                    model: "gpt-4o",
                    messages: [{ role: "user", content: prompt }]
                }, {
                    headers: {
                        'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
                        'Content-Type': 'application/json'
                    }
                });
                markdown = openaiRes.data.choices[0].message.content;
                break;

            case 'gemini':
                const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${process.env.GEMINI_API_KEY}`;
                const geminiPayload = {
                    contents: [{
                        parts: [{ text: prompt }]
                    }]
                };
                const geminiRes = await axios.post(geminiUrl, geminiPayload, {
                    headers: { 'Content-Type': 'application/json' }
                });

                if (geminiRes.data && geminiRes.data.candidates && geminiRes.data.candidates[0].content) {
                    markdown = geminiRes.data.candidates[0].content.parts[0].text;
                } else {
                    throw new Error("Invalid response from Gemini API");
                }
                break;

            case 'mock':
                markdown = `# Converted Document\n\nThis is a **mock conversion** based on your input:\n\n> ${text.substring(0, 100)}${text.length > 100 ? '...' : ''}\n\n### Key points detected:\n- Automatic formatting applied\n- AI logic simulated\n\n---\n*Generated by Mdify Mock Engine*`;
                break;

            case 'groq':
                const groqResponse = await axios.post('https://api.groq.com/openai/v1/chat/completions', {
                    model: "llama-3.3-70b-versatile",
                    messages: [{ role: "user", content: prompt }]
                }, {
                    headers: {
                        'Authorization': `Bearer ${process.env.GROQ_API_KEY}`,
                        'Content-Type': 'application/json'
                    }
                });
                markdown = groqResponse.data.choices[0].message.content;
                break;

            default:
                throw new Error("Invalid provider");
        }

        return {
            statusCode: 200,
            headers,
            body: JSON.stringify({ markdown })
        };
    } catch (error) {
        console.error("Error converting to markdown:", error);
        const errorMessage = error.response?.data?.error?.message || error.message;
        return {
            statusCode: 500,
            headers,
            body: JSON.stringify({ error: "Failed to convert text to markdown", details: errorMessage })
        };
    }
};
