const express = require('express');
const cors = require('cors');
const bodyParser = require('body-parser');
const dotenv = require('dotenv');
const { OpenAI } = require('openai');
const { GoogleGenerativeAI } = require("@google/generative-ai");
const axios = require('axios');

dotenv.config();

const app = express();
const port = process.env.PORT || 3000;

app.use(cors());
app.use(bodyParser.json());

// AI Provider Clients
const getOpenAIClient = () => new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
const getGeminiClient = () => new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

const convertToMarkdown = async (text, provider) => {
    const prompt = `Convert the following text into a well-formatted Markdown document. Use appropriate headers, lists, and formatting to make it look professional. Do not add any conversational text before or after the markdown. Just return the markdown content.\n\nText:\n${text}`;

    try {
        switch (provider) {
            case 'openai':
                const openai = getOpenAIClient();
                const response = await openai.chat.completions.create({
                    model: "gpt-4o",
                    messages: [{ role: "user", content: prompt }],
                });
                return response.choices[0].message.content;

            case 'gemini':
                const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${process.env.GEMINI_API_KEY}`;
                const geminiPayload = {
                    contents: [{
                        parts: [{ text: prompt }]
                    }]
                };
                const geminiRes = await axios.post(geminiUrl, geminiPayload, {
                    headers: { 'Content-Type': 'application/json' }
                });

                if (geminiRes.data && geminiRes.data.candidates && geminiRes.data.candidates[0].content) {
                    return geminiRes.data.candidates[0].content.parts[0].text;
                }
                throw new Error("Invalid response from Gemini API");

            case 'mock':
                // Simple mock conversion for testing without API keys
                return `# Converted Document\n\nThis is a **mock conversion** based on your input:\n\n> ${text.substring(0, 100)}${text.length > 100 ? '...' : ''}\n\n### Key points detected:\n- Automatic formatting applied\n- AI logic simulated\n\n---\n*Generated by Mdify Mock Engine*`;

            case 'grok':
                // Using GroqCloud (groq.com) - Fast and has a good free tier
                const groqResponse = await axios.post('https://api.groq.com/openai/v1/chat/completions', {
                    model: "llama-3.3-70b-versatile",
                    messages: [{ role: "user", content: prompt }]
                }, {
                    headers: {
                        'Authorization': `Bearer ${process.env.GROK_API_KEY}`,
                        'Content-Type': 'application/json'
                    }
                });
                return groqResponse.data.choices[0].message.content;

            default:
                throw new Error("Invalid provider");
        }
    } catch (error) {
        if (error.response && error.response.data) {
            throw new Error(JSON.stringify(error.response.data));
        }
        throw error;
    }
};

app.post('/api/convert', async (req, res) => {
    const { text, provider } = req.body;

    if (!text) {
        return res.status(400).json({ error: "Text is required" });
    }

    const aiProvider = provider || process.env.DEFAULT_AI_PROVIDER || 'gemini';
    console.log(`Conversion request received. Provider: ${aiProvider}`);

    try {
        const markdown = await convertToMarkdown(text, aiProvider);
        res.json({ markdown });
    } catch (error) {
        console.error("Error converting to markdown:", error);
        res.status(500).json({ error: "Failed to convert text to markdown", details: error.message });
    }
});

app.listen(port, () => {
    console.log(`Server running at http://localhost:${port}`);
});
